apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-microservice
  namespace: prod
  labels:
    app: spring-microservice
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-microservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: spring-microservice
        env: prod
    spec:
      containers:
        - name: app
          image: shwetang95/spring-microservice:main-06ed48e
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-microservice-config
            - secretRef:
                name: spring-microservice-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
