apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-microservice
  namespace: dev
  labels:
    app: spring-microservice
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-microservice
  template:
    metadata:
      labels:
        app: spring-microservice
        env: dev
    spec:
      containers:
        - name: app
          image: shwetang95/spring-microservice:v1.0.4
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-microservice-config
            - secretRef:
                name: spring-microservice-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
