apiVersion: v1
kind: Service
metadata:
  name: spring-microservice
  namespace: dev
  labels:
    app: spring-microservice
spec:
  type: NodePort
  selector:
    app: spring-microservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
